### ISSUE TITLE
Question: Clarifications about SecureArray

### ISSUE THREAD

**Issue by Abscissa** [etcimon/memutils#14]
Wanted to make sure I'm understanding this aspect of the library correctly:

If I use `SecureArray!ubyte` as a drop-in replacement for `ubyte[]`, does that mean the memory gets zeroed out immediately once the reference count reaches zero?

Also, I noticed some things in the secure allocator that seemed to indicate that in certain situations (determined at compile-time) the memory allocated by the secure allocator won't be saved to disk during (for example) hibernation. That sounds interesting, but I couldn't quite work out what determines whether that behavior is compiled in or not. Also, if that does occur, what effect does that have when the program is resumed? Does any access to the memory become a segfault? Is it simply zeroed? If it's zeroed, doesn't that mean that if, for example, the memory was being used to store a user's new password, that the memory should be checked before computing the hash to be stored to DB so the user's password doesn't end up becoming empty string or "\0\0\0\0\0...", etc?

**Comment by etcimon** [comment]
Hello,

This part of the memory management is handled in https://github.com/etcimon/memutils and compiled with the version flag "SecurePool" as seen here https://github.com/etcimon/memutils/blob/master/source/memutils/constants.d#L19 and here https://github.com/etcimon/memutils/blob/master/source/memutils/securepool.d#L14

The memory setting is implemented with `VirtualLock` on Windows, and you're right it may be written to disk during hibernation or with a VM snapshot as specified here: https://blogs.msdn.microsoft.com/oldnewthing/20140207-00/?p=1833

On posix this is handled with `mlock` http://pubs.opengroup.org/onlinepubs/009695399/functions/mlock.html

All memory is also automatically zeroed when freed as seen here: https://github.com/etcimon/memutils/blob/master/source/memutils/cryptosafe.d#L119

**Comment by Abscissa** [comment]
>The memory setting is implemented with VirtualLock on Windows, and you're right it may be written to disk during hibernation or with a VM snapshot as specified here: https://blogs.msdn.microsoft.com/oldnewthing/20140207-00/?p=1833
>
>On posix this is handled with mlock http://pubs.opengroup.org/onlinepubs/009695399/functions/mlock.html

Oh, ok., I think I misunderstood before.

So:  IIUC, memory locking (which is enabled on the secure memory allocator if-and-only-if a project using memutils manually defines version flag "SecurePool") simply prevents a block of memory from being paged to disk during normal memory paging (but not during hibernate). If so, that sounds like its would be safe, and indeed preferable, for passwords, etc.

>All memory is also automatically zeroed when freed as seen here: https://github.com/etcimon/memutils/blob/master/source/memutils/cryptosafe.d#L119

And, to be clear, for SecureArray that occurs when SecureArray's refcount reaches 0, NOT at the the next garbage-collection cycle after the refcount hits 0, right?

**Comment by etcimon** [comment]
> And, to be clear, for SecureArray that occurs when SecureArray's refcount reaches 0, NOT at the the next garbage-collection cycle after the refcount hits 0, right?

Exactly, the SecureArray is implemented with this Allocator which is deterministic, not through garbage collection. However, it plays nice with garbage collection because live data segments containing pointers will be added with "GC.addRange". However, for ubyte[], the garbage collector isn't even at play here, it's purely RAII and reference counting. With SecureVector, there is no reference counting at all.

**Comment by etcimon** [comment]
This is useful for passwords yes. For example you've encrypted a data block and the encryption software ended up swapping for any random reason. Someone that steals your computer could physically find that password on the hard drive along with the data, effectively making the encryption purposeless in the first place..

**Comment by Abscissa** [comment]
Ok, great, on both things.

Something I misread looking through the source led me to incorrectly believe that the SecurePool stuff meant the memory would NOT be saved to disk during hibernation and other similar unspecified events. Which led me to worry about "Well, shoot, does that mean, from the application's perspective, a password could suddenly become zeroed out before it's hash is computed and stored?" I see now this is not the case.

Thanks on a very handy lib, btw.
