### ISSUE TITLE
Errors on dmd 2.085.0

### ISSUE THREAD

**Issue by Boris-Barboris** [etcimon/memutils#18]
Tests fail at memutils.tests.vectorArrayTest because of not deallocated 11-byte block, generated on memutils.vector.Vector!(ubyte, memutils.utils.AppMem).Vector.dupr()

Refcounted no longer works with Vector and breaks botan, because the code snippet
```
private void defaultInit() const {
                static if (__traits(compiles, { this.opCall(); }()) {
                        if (!m_object) {
                                auto newObj = this.opCall();
                                (cast(RefCounted*)&this).m_object = newObj.m_object;
                                (cast(RefCounted*)&this).m_refCount = newObj.m_refCount;
                                newObj.m_object = null;
                        }
                }
        }
```
no longer works as intended for Vector under dmd. The test ```__traits(compiles, { this.opCall(); }()``` fails for Vector, however the opCall() can be made, and the trait will actually return true when placed after (lower in the source code) the templated opCall instantiation.

**Comment by Geod24** [comment]
Fixed in https://github.com/etcimon/memutils/commit/46a147addb3ee9d7a14727ef39b37b115680012f
