### ISSUE TITLE
Compilation error with LDC

### ISSUE THREAD

**Issue by bagomot** [etcimon/memutils#19]
Compilation error with LDC 1.27.0-beta3:

memutils-1.0.4\memutils\source\memutils\allocators.d(18,8): Error: module `std.exception` import `enforceEx` not found, did you mean template `std.exception.enforce(E : Throwable = Exception) if (is(typeof(new E("", string.init, size_t.init)) : Throwable) || is(typeof(new E(string.init, size_t.init)) : Throwable))`?

**Comment by bagomot** [comment]
UPD: With DMD v2.097.1-dirty the same error.

**Comment by chances** [comment]
I've reproduced this error via LDC 1.28.0 based on DMD v2.098.0 and LLVM 12.0.1

However, it seems this issue is resolved on the `master` branch.

**Comment by chances** [comment]
`enforceEx` has been removed from the standard library: https://dlang.org/changelog/2.097.0.html#std-exception

**Comment by p-mitana** [comment]
I see that the code is already fixed. Could you please tag a new release? This error prevents botan from building.

**Comment by cyrusmsk** [comment]
@etcimon could you please approve the PR for libasync and memutils?

**Comment by shakor0** [comment]
Yes, could we please get an updated version?
We have projects that are frozen to older dmd and or ldc compilers as we are dependent on this project.
Thanks

**Comment by etcimon** [comment]
This should be fixed, note that I disabled .dup in favor of .clone
