### ISSUE TITLE
Problem to use on M1 chip

### ISSUE THREAD

**Issue by cyrusmsk** [etcimon/memutils#20]
/.dub/packages/memutils-1.0.6/memutils/source/memutils/scoped.d(156,15): Error: DMD-style `asm { op; }` statements are not supported for the "arm64" architecture.
/.dub/packages/memutils-1.0.6/memutils/source/memutils/scoped.d(156,15):        Use GDC-style `asm { "op" : …; }` syntax or `ldc.llvmasm.__asm` instead.

It seems dmd-style used.

**Comment by etcimon** [comment]
Should be fixed for the new version tag
