### ISSUE TITLE
Deprecation: using "in ref"

### ISSUE THREAD

**Issue by andrewlalis** [etcimon/memutils#21]
I'm using memutils v1.0.10, and get the following deprecation warning when compiling my project with dub:

```
../../../../.dub/packages/memutils/1.0.10/memutils/source/memutils/hashmap.d(135,30): Deprecation: using `in ref` is deprecated, use `-preview=in` and `in` instead
```

Just something to be aware of, and potentially fix before `in ref` is removed.

**Comment by etcimon** [comment]
Thanks!
