### ISSUE TITLE
Cycle between modules with module dtor on LDC 0.16.0-beta1

### ISSUE THREAD

**Issue by s-ludwig** [etcimon/memutils#4]
See https://travis-ci.org/rejectedsoftware/vibe.d/jobs/84628252

```
object.Exception@/build/src/ldc/runtime/druntime/src/rt/minfo.d(162): Aborting: Cycle detected between modules with ctors/dtors:
memutils.allocators -> memutils.cryptosafe -> memutils.allocators
```

Could be solved using singleton construction, or by explicitly calling an initialization function in cryptosafe from `allocators`' static constructor.

BTW, shouldn't `SecureAllocator.ms_zeroise` and `ms_deinit` be defined outside of `SecureAllocator`? Currently there will be one  `SecurePool` per `SecureAllocator` template instance, but it looks like a single one would be sufficient. That would at least make it easier to define a `package void initCryptoSafe()` function.

**Comment by etcimon** [comment]
I had been pondering the idea of making these allocators portable eventually, but I realize they probably never will be managed outside of memutils. So, yes, the singleton idea in the allocators module is what I will be doing
