### ISSUE TITLE
Compile errors for DMD 2.070.0-b1

### ISSUE THREAD

**Issue by s-ludwig** [etcimon/memutils#7]
https://travis-ci.org/rejectedsoftware/vibe.d/jobs/101533036

**Comment by etcimon** [comment]
Maybe it has something to do with libasync 0.7.5 -> 0.7.7 upgrade not being done? I can't reproduce it on my end, is there a way I can see which dub command was used?

**Comment by s-ludwig** [comment]
Hm looks like the issue was just that 0.4.4 wasn't available on code.dlang.org - it now compiles after a simple restart. Did you change anything for the tag?

**Comment by etcimon** [comment]
Yes, the patch was in ~master only, so I added the 0.4.4 tag yesterday
